require "util"
require "Class"
require "Event"
require "data.Static"
require "data.constant"
require "Global.Timer"

require "views.Dark"
require "display"
require "ui"
require "Global.director"
require "Global.User"
require "model.HttpController"
require "Global.GlobalController"

require "views.ShadowWords"

require "views.MoveMap"
require "busiViews.BuildLayer"
require "views.StandardTouchHandler"
require "views.ResLackBanner"
require "views.Store"
require "views.ChildMenuLayer"
require "views.CastleScene"
require "views.Loading"
